packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@types/react': ^18.2.0
  react: ^18.2.0
  rolldown: 1.0.0-beta.34
  rolldown-plugin-dts: ^0.15.9
  rollup-plugin-visualizer: ^6.0.3
  svgo: ^3.2.0
  vue: ^3.4.0
catalogs:
  cli:
    '@antfu/eslint-config': ^4.10.1
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    vite: ^6.2.1
  types:
    '@types/node': ^22.13.10
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
